### ISSUE TITLE
Wont open

### ISSUE THREAD

**Issue by Drellen1** [DuncanRuns/AutomaticMinecraftTimer#19]
I says Fatal error dected Failed to execute script AutoMCTimer.

**Comment by DuncanRuns** [comment]
Hi! If you are still having issues, could you please post the output of the debug version found here: https://github.com/DuncanRuns/AutomaticMinecraftTimer/releases/download/v2.4.0/AutoMCTimerCrashDebug.exe

**Comment by DuncanRuns** [comment]
I believe this issue is fixed in v2.4.1, if you are still having issues you can contact me on discord: Duncan#1627
